// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: pb/exchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//--------------------------------管理员--------------------------------
type Admin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  //id
	RoleId     int64  `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`          //角色组
	Account    string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`         //用户名
	Nickname   string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`       //昵称
	Mobile     string `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`           //手机号
	Password   string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`       //密码
	Salt       string `protobuf:"bytes,7,opt,name=salt,proto3" json:"salt,omitempty"`               //密码盐
	Avatar     string `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`           //头像
	Email      string `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`             //邮箱
	LoginFail  int64  `protobuf:"varint,10,opt,name=loginFail,proto3" json:"loginFail,omitempty"`   //登录失败次数
	LoginTime  int64  `protobuf:"varint,11,opt,name=loginTime,proto3" json:"loginTime,omitempty"`   //登录时间
	LoginIp    string `protobuf:"bytes,12,opt,name=loginIp,proto3" json:"loginIp,omitempty"`        //登录 ip
	Status     string `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`          //状态
	CreateTime int64  `protobuf:"varint,14,opt,name=createTime,proto3" json:"createTime,omitempty"` //创建时间
	UpdateTime int64  `protobuf:"varint,15,opt,name=updateTime,proto3" json:"updateTime,omitempty"` //更新时间
}

func (x *Admin) Reset() {
	*x = Admin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Admin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Admin) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *Admin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Admin) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Admin) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Admin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Admin) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *Admin) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Admin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Admin) GetLoginFail() int64 {
	if x != nil {
		return x.LoginFail
	}
	return 0
}

func (x *Admin) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *Admin) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *Admin) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Admin) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Admin) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type AdminAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId     int64  `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`          //角色组
	Account    string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`         //用户名
	Nickname   string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`       //昵称
	Mobile     string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`           //手机号
	Password   string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`       //密码
	Secret     string `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`           //秘钥
	Salt       string `protobuf:"bytes,7,opt,name=salt,proto3" json:"salt,omitempty"`               //密码盐
	Avatar     string `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`           //头像
	Email      string `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`             //邮箱
	LoginFail  int64  `protobuf:"varint,10,opt,name=loginFail,proto3" json:"loginFail,omitempty"`   //登录失败次数
	LoginTime  int64  `protobuf:"varint,11,opt,name=loginTime,proto3" json:"loginTime,omitempty"`   //登录时间
	LoginIp    string `protobuf:"bytes,12,opt,name=loginIp,proto3" json:"loginIp,omitempty"`        //登录 ip
	Status     string `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`          //状态
	CreateTime int64  `protobuf:"varint,14,opt,name=createTime,proto3" json:"createTime,omitempty"` //创建时间
	UpdateTime int64  `protobuf:"varint,15,opt,name=updateTime,proto3" json:"updateTime,omitempty"` //更新时间
}

func (x *AdminAddReq) Reset() {
	*x = AdminAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAddReq) ProtoMessage() {}

func (x *AdminAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAddReq.ProtoReflect.Descriptor instead.
func (*AdminAddReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *AdminAddReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AdminAddReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AdminAddReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminAddReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AdminAddReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminAddReq) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AdminAddReq) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *AdminAddReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminAddReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminAddReq) GetLoginFail() int64 {
	if x != nil {
		return x.LoginFail
	}
	return 0
}

func (x *AdminAddReq) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *AdminAddReq) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *AdminAddReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminAddReq) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AdminAddReq) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type AdminAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminAddResp) Reset() {
	*x = AdminAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAddResp) ProtoMessage() {}

func (x *AdminAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAddResp.ProtoReflect.Descriptor instead.
func (*AdminAddResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{2}
}

type AdminUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  //id
	RoleId     int64  `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`          //角色组
	Account    string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`         //用户名
	Nickname   string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`       //昵称
	Mobile     string `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`           //手机号
	Password   string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`       //密码
	Secret     string `protobuf:"bytes,7,opt,name=secret,proto3" json:"secret,omitempty"`           //秘钥
	Salt       string `protobuf:"bytes,8,opt,name=salt,proto3" json:"salt,omitempty"`               //密码盐
	Avatar     string `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`           //头像
	Email      string `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`            //邮箱
	LoginFail  int64  `protobuf:"varint,11,opt,name=loginFail,proto3" json:"loginFail,omitempty"`   //登录失败次数
	LoginTime  int64  `protobuf:"varint,12,opt,name=loginTime,proto3" json:"loginTime,omitempty"`   //登录时间
	LoginIp    string `protobuf:"bytes,13,opt,name=loginIp,proto3" json:"loginIp,omitempty"`        //登录 ip
	Status     string `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`          //状态
	CreateTime int64  `protobuf:"varint,15,opt,name=createTime,proto3" json:"createTime,omitempty"` //创建时间
	UpdateTime int64  `protobuf:"varint,16,opt,name=updateTime,proto3" json:"updateTime,omitempty"` //更新时间
}

func (x *AdminUpdateReq) Reset() {
	*x = AdminUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateReq) ProtoMessage() {}

func (x *AdminUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateReq.ProtoReflect.Descriptor instead.
func (*AdminUpdateReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUpdateReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AdminUpdateReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AdminUpdateReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminUpdateReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AdminUpdateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminUpdateReq) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AdminUpdateReq) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *AdminUpdateReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminUpdateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUpdateReq) GetLoginFail() int64 {
	if x != nil {
		return x.LoginFail
	}
	return 0
}

func (x *AdminUpdateReq) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *AdminUpdateReq) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *AdminUpdateReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminUpdateReq) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AdminUpdateReq) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type AdminUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminUpdateResp) Reset() {
	*x = AdminUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateResp) ProtoMessage() {}

func (x *AdminUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateResp.ProtoReflect.Descriptor instead.
func (*AdminUpdateResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{4}
}

type AdminDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *AdminDeleteReq) Reset() {
	*x = AdminDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteReq) ProtoMessage() {}

func (x *AdminDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteReq.ProtoReflect.Descriptor instead.
func (*AdminDeleteReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *AdminDeleteReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminDeleteResp) Reset() {
	*x = AdminDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteResp) ProtoMessage() {}

func (x *AdminDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteResp.ProtoReflect.Descriptor instead.
func (*AdminDeleteResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{6}
}

type AdminDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          //id
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"` //用户名
}

func (x *AdminDetailsReq) Reset() {
	*x = AdminDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDetailsReq) ProtoMessage() {}

func (x *AdminDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDetailsReq.ProtoReflect.Descriptor instead.
func (*AdminDetailsReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *AdminDetailsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminDetailsReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type AdminDetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  //id
	RoleId     int64  `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`          //角色组
	Account    string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`         //用户名
	Nickname   string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`       //昵称
	Mobile     string `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`           //手机号
	Password   string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`       //密码
	Secret     string `protobuf:"bytes,7,opt,name=secret,proto3" json:"secret,omitempty"`           //秘钥
	Salt       string `protobuf:"bytes,8,opt,name=salt,proto3" json:"salt,omitempty"`               //密码盐
	Avatar     string `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`           //头像
	Email      string `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`            //邮箱
	LoginFail  int64  `protobuf:"varint,11,opt,name=loginFail,proto3" json:"loginFail,omitempty"`   //登录失败次数
	LoginTime  int64  `protobuf:"varint,12,opt,name=loginTime,proto3" json:"loginTime,omitempty"`   //登录时间
	LoginIp    string `protobuf:"bytes,13,opt,name=loginIp,proto3" json:"loginIp,omitempty"`        //登录 ip
	Status     string `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`          //状态
	CreateTime int64  `protobuf:"varint,15,opt,name=createTime,proto3" json:"createTime,omitempty"` //创建时间
	UpdateTime int64  `protobuf:"varint,16,opt,name=updateTime,proto3" json:"updateTime,omitempty"` //更新时间
}

func (x *AdminDetailsResp) Reset() {
	*x = AdminDetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDetailsResp) ProtoMessage() {}

func (x *AdminDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDetailsResp.ProtoReflect.Descriptor instead.
func (*AdminDetailsResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{8}
}

func (x *AdminDetailsResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminDetailsResp) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AdminDetailsResp) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AdminDetailsResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminDetailsResp) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AdminDetailsResp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AdminDetailsResp) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AdminDetailsResp) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *AdminDetailsResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminDetailsResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminDetailsResp) GetLoginFail() int64 {
	if x != nil {
		return x.LoginFail
	}
	return 0
}

func (x *AdminDetailsResp) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *AdminDetailsResp) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *AdminDetailsResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminDetailsResp) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AdminDetailsResp) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type AdminSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNo     int64  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`        //pageNo
	PageSize   int64  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`    //pageSize
	OrderField string `protobuf:"bytes,3,opt,name=orderField,proto3" json:"orderField,omitempty"` //排序字段
	OrderParam string `protobuf:"bytes,4,opt,name=orderParam,proto3" json:"orderParam,omitempty"` //排序方法
	StartTime  int64  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`  //开始时间
	EndTime    int64  `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`      //结束时间
}

func (x *AdminSearchReq) Reset() {
	*x = AdminSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSearchReq) ProtoMessage() {}

func (x *AdminSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSearchReq.ProtoReflect.Descriptor instead.
func (*AdminSearchReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{9}
}

func (x *AdminSearchReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *AdminSearchReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminSearchReq) GetOrderField() string {
	if x != nil {
		return x.OrderField
	}
	return ""
}

func (x *AdminSearchReq) GetOrderParam() string {
	if x != nil {
		return x.OrderParam
	}
	return ""
}

func (x *AdminSearchReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AdminSearchReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type AdminSearchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` //总条数
	List  []*Admin `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`    //admin
}

func (x *AdminSearchResp) Reset() {
	*x = AdminSearchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSearchResp) ProtoMessage() {}

func (x *AdminSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSearchResp.ProtoReflect.Descriptor instead.
func (*AdminSearchResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{10}
}

func (x *AdminSearchResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminSearchResp) GetList() []*Admin {
	if x != nil {
		return x.List
	}
	return nil
}

//--------------------------------菜单权限--------------------------------
type Access struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`             //id
	ParentId int64  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"` //上级ID
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`          //权限标识
	Title    string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`        //菜单名称
	Type     string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`          //类型
	Icon     string `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`          //图标
	Params   string `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`      //参数
	Weigh    int64  `protobuf:"varint,8,opt,name=weigh,proto3" json:"weigh,omitempty"`       //权重
	Status   string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`      //状态
}

func (x *Access) Reset() {
	*x = Access{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Access) ProtoMessage() {}

func (x *Access) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Access.ProtoReflect.Descriptor instead.
func (*Access) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{11}
}

func (x *Access) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Access) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Access) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Access) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Access) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Access) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Access) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Access) GetWeigh() int64 {
	if x != nil {
		return x.Weigh
	}
	return 0
}

func (x *Access) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AccessAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentId int64  `protobuf:"varint,1,opt,name=parentId,proto3" json:"parentId,omitempty"` //上级ID
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`          //权限标识
	Title    string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`        //菜单名称
	Type     string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`          //类型
	Icon     string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`          //图标
	Params   string `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`      //参数
	Weigh    int64  `protobuf:"varint,7,opt,name=weigh,proto3" json:"weigh,omitempty"`       //权重
	Status   string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`      //状态
}

func (x *AccessAddReq) Reset() {
	*x = AccessAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessAddReq) ProtoMessage() {}

func (x *AccessAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessAddReq.ProtoReflect.Descriptor instead.
func (*AccessAddReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{12}
}

func (x *AccessAddReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AccessAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessAddReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AccessAddReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccessAddReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AccessAddReq) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *AccessAddReq) GetWeigh() int64 {
	if x != nil {
		return x.Weigh
	}
	return 0
}

func (x *AccessAddReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AccessAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccessAddResp) Reset() {
	*x = AccessAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessAddResp) ProtoMessage() {}

func (x *AccessAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessAddResp.ProtoReflect.Descriptor instead.
func (*AccessAddResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{13}
}

type AccessUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`             //id
	ParentId int64  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"` //上级ID
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`          //权限标识
	Title    string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`        //菜单名称
	Type     string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`          //类型
	Icon     string `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`          //图标
	Params   string `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`      //参数
	Weigh    int64  `protobuf:"varint,8,opt,name=weigh,proto3" json:"weigh,omitempty"`       //权重
	Status   string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`      //状态
}

func (x *AccessUpdateReq) Reset() {
	*x = AccessUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessUpdateReq) ProtoMessage() {}

func (x *AccessUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessUpdateReq.ProtoReflect.Descriptor instead.
func (*AccessUpdateReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{14}
}

func (x *AccessUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccessUpdateReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AccessUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessUpdateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AccessUpdateReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccessUpdateReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AccessUpdateReq) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *AccessUpdateReq) GetWeigh() int64 {
	if x != nil {
		return x.Weigh
	}
	return 0
}

func (x *AccessUpdateReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AccessUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccessUpdateResp) Reset() {
	*x = AccessUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessUpdateResp) ProtoMessage() {}

func (x *AccessUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessUpdateResp.ProtoReflect.Descriptor instead.
func (*AccessUpdateResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{15}
}

type AccessDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *AccessDeleteReq) Reset() {
	*x = AccessDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessDeleteReq) ProtoMessage() {}

func (x *AccessDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessDeleteReq.ProtoReflect.Descriptor instead.
func (*AccessDeleteReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{16}
}

func (x *AccessDeleteReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AccessDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccessDeleteResp) Reset() {
	*x = AccessDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessDeleteResp) ProtoMessage() {}

func (x *AccessDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessDeleteResp.ProtoReflect.Descriptor instead.
func (*AccessDeleteResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{17}
}

type AccessDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *AccessDetailsReq) Reset() {
	*x = AccessDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessDetailsReq) ProtoMessage() {}

func (x *AccessDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessDetailsReq.ProtoReflect.Descriptor instead.
func (*AccessDetailsReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{18}
}

func (x *AccessDetailsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AccessDetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`             //id
	ParentId int64  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"` //上级ID
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`          //权限标识
	Title    string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`        //菜单名称
	Type     string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`          //类型
	Icon     string `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`          //图标
	Params   string `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`      //参数
	Weigh    int64  `protobuf:"varint,8,opt,name=weigh,proto3" json:"weigh,omitempty"`       //权重
	Status   string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`      //状态
}

func (x *AccessDetailsResp) Reset() {
	*x = AccessDetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessDetailsResp) ProtoMessage() {}

func (x *AccessDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessDetailsResp.ProtoReflect.Descriptor instead.
func (*AccessDetailsResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{19}
}

func (x *AccessDetailsResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccessDetailsResp) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *AccessDetailsResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessDetailsResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AccessDetailsResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccessDetailsResp) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AccessDetailsResp) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *AccessDetailsResp) GetWeigh() int64 {
	if x != nil {
		return x.Weigh
	}
	return 0
}

func (x *AccessDetailsResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AccessSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNo     int64  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`        //pageNo
	PageSize   int64  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`    //pageSize
	OrderField string `protobuf:"bytes,3,opt,name=orderField,proto3" json:"orderField,omitempty"` //排序字段
	OrderParam string `protobuf:"bytes,4,opt,name=orderParam,proto3" json:"orderParam,omitempty"` //排序方法
	StartTime  int64  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`  //开始时间
	EndTime    int64  `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`      //结束时间
}

func (x *AccessSearchReq) Reset() {
	*x = AccessSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSearchReq) ProtoMessage() {}

func (x *AccessSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSearchReq.ProtoReflect.Descriptor instead.
func (*AccessSearchReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{20}
}

func (x *AccessSearchReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *AccessSearchReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AccessSearchReq) GetOrderField() string {
	if x != nil {
		return x.OrderField
	}
	return ""
}

func (x *AccessSearchReq) GetOrderParam() string {
	if x != nil {
		return x.OrderParam
	}
	return ""
}

func (x *AccessSearchReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AccessSearchReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type AccessSearchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` //总条数
	List  []*Access `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`    //acces
}

func (x *AccessSearchResp) Reset() {
	*x = AccessSearchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSearchResp) ProtoMessage() {}

func (x *AccessSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSearchResp.ProtoReflect.Descriptor instead.
func (*AccessSearchResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{21}
}

func (x *AccessSearchResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AccessSearchResp) GetList() []*Access {
	if x != nil {
		return x.List
	}
	return nil
}

type AccessListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNo     int64    `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`        //pageNo
	PageSize   int64    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`    //pageSize
	OrderField string   `protobuf:"bytes,3,opt,name=orderField,proto3" json:"orderField,omitempty"` //排序字段
	OrderParam string   `protobuf:"bytes,4,opt,name=orderParam,proto3" json:"orderParam,omitempty"` //排序方法
	StartTime  int64    `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`  //开始时间
	EndTime    int64    `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`      //结束时间
	Type       string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`             //类型
	Status     string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`         //状态
	Rules      []string `protobuf:"bytes,9,rep,name=Rules,proto3" json:"Rules,omitempty"`           //权限
}

func (x *AccessListReq) Reset() {
	*x = AccessListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessListReq) ProtoMessage() {}

func (x *AccessListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessListReq.ProtoReflect.Descriptor instead.
func (*AccessListReq) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{22}
}

func (x *AccessListReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *AccessListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AccessListReq) GetOrderField() string {
	if x != nil {
		return x.OrderField
	}
	return ""
}

func (x *AccessListReq) GetOrderParam() string {
	if x != nil {
		return x.OrderParam
	}
	return ""
}

func (x *AccessListReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AccessListReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *AccessListReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccessListReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccessListReq) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AccessListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Access `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"` //acces
}

func (x *AccessListResp) Reset() {
	*x = AccessListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_exchange_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessListResp) ProtoMessage() {}

func (x *AccessListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_exchange_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessListResp.ProtoReflect.Descriptor instead.
func (*AccessListResp) Descriptor() ([]byte, []int) {
	return file_pb_exchange_proto_rawDescGZIP(), []int{23}
}

func (x *AccessListResp) GetList() []*Access {
	if x != nil {
		return x.List
	}
	return nil
}

var File_pb_exchange_proto protoreflect.FileDescriptor

var file_pb_exchange_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x03, 0x0a, 0x05, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46,
	0x61, 0x69, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x46, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x97, 0x03, 0x0a, 0x0b, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x0e,
	0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0xaa,
	0x03, 0x0a, 0x0e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x49, 0x70, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x20,
	0x0a, 0x0e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x3b, 0x0a, 0x0f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xac, 0x03, 0x0a, 0x10, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0xbc, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x46,
	0x0a, 0x0f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xcc, 0x01, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x65, 0x69, 0x67, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0xd5, 0x01, 0x0a, 0x0f,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x69, 0x67, 0x68, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x65, 0x69, 0x67, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x22,
	0x0a, 0x10, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x65, 0x69, 0x67, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xbd, 0x01, 0x0a,
	0x0f, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x10,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xfd, 0x01, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65,
	0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x9c, 0x02, 0x0a, 0x08, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64,
	0x64, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x36, 0x0a, 0x0b, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_exchange_proto_rawDescOnce sync.Once
	file_pb_exchange_proto_rawDescData = file_pb_exchange_proto_rawDesc
)

func file_pb_exchange_proto_rawDescGZIP() []byte {
	file_pb_exchange_proto_rawDescOnce.Do(func() {
		file_pb_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_exchange_proto_rawDescData)
	})
	return file_pb_exchange_proto_rawDescData
}

var file_pb_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pb_exchange_proto_goTypes = []interface{}{
	(*Admin)(nil),             // 0: pb.Admin
	(*AdminAddReq)(nil),       // 1: pb.AdminAddReq
	(*AdminAddResp)(nil),      // 2: pb.AdminAddResp
	(*AdminUpdateReq)(nil),    // 3: pb.AdminUpdateReq
	(*AdminUpdateResp)(nil),   // 4: pb.AdminUpdateResp
	(*AdminDeleteReq)(nil),    // 5: pb.AdminDeleteReq
	(*AdminDeleteResp)(nil),   // 6: pb.AdminDeleteResp
	(*AdminDetailsReq)(nil),   // 7: pb.AdminDetailsReq
	(*AdminDetailsResp)(nil),  // 8: pb.AdminDetailsResp
	(*AdminSearchReq)(nil),    // 9: pb.AdminSearchReq
	(*AdminSearchResp)(nil),   // 10: pb.AdminSearchResp
	(*Access)(nil),            // 11: pb.Access
	(*AccessAddReq)(nil),      // 12: pb.AccessAddReq
	(*AccessAddResp)(nil),     // 13: pb.AccessAddResp
	(*AccessUpdateReq)(nil),   // 14: pb.AccessUpdateReq
	(*AccessUpdateResp)(nil),  // 15: pb.AccessUpdateResp
	(*AccessDeleteReq)(nil),   // 16: pb.AccessDeleteReq
	(*AccessDeleteResp)(nil),  // 17: pb.AccessDeleteResp
	(*AccessDetailsReq)(nil),  // 18: pb.AccessDetailsReq
	(*AccessDetailsResp)(nil), // 19: pb.AccessDetailsResp
	(*AccessSearchReq)(nil),   // 20: pb.AccessSearchReq
	(*AccessSearchResp)(nil),  // 21: pb.AccessSearchResp
	(*AccessListReq)(nil),     // 22: pb.AccessListReq
	(*AccessListResp)(nil),    // 23: pb.AccessListResp
}
var file_pb_exchange_proto_depIdxs = []int32{
	0,  // 0: pb.AdminSearchResp.list:type_name -> pb.Admin
	11, // 1: pb.AccessSearchResp.list:type_name -> pb.Access
	11, // 2: pb.AccessListResp.list:type_name -> pb.Access
	1,  // 3: pb.Exchange.AdminAdd:input_type -> pb.AdminAddReq
	3,  // 4: pb.Exchange.AdminUpdate:input_type -> pb.AdminUpdateReq
	5,  // 5: pb.Exchange.AdminDelete:input_type -> pb.AdminDeleteReq
	7,  // 6: pb.Exchange.AdminDetails:input_type -> pb.AdminDetailsReq
	9,  // 7: pb.Exchange.AdminSearch:input_type -> pb.AdminSearchReq
	2,  // 8: pb.Exchange.AdminAdd:output_type -> pb.AdminAddResp
	4,  // 9: pb.Exchange.AdminUpdate:output_type -> pb.AdminUpdateResp
	6,  // 10: pb.Exchange.AdminDelete:output_type -> pb.AdminDeleteResp
	8,  // 11: pb.Exchange.AdminDetails:output_type -> pb.AdminDetailsResp
	10, // 12: pb.Exchange.AdminSearch:output_type -> pb.AdminSearchResp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_exchange_proto_init() }
func file_pb_exchange_proto_init() {
	if File_pb_exchange_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_exchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Admin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminDetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminSearchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Access); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessDetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessSearchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_exchange_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_exchange_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_exchange_proto_goTypes,
		DependencyIndexes: file_pb_exchange_proto_depIdxs,
		MessageInfos:      file_pb_exchange_proto_msgTypes,
	}.Build()
	File_pb_exchange_proto = out.File
	file_pb_exchange_proto_rawDesc = nil
	file_pb_exchange_proto_goTypes = nil
	file_pb_exchange_proto_depIdxs = nil
}
